### ISSUE TITLE
TODO (v1.0)

### ISSUE THREAD

**Issue by rstacruz** [rstacruz/devhints-engine#10]
## :fire: Sheet page

- [x] Mini-Markdown (#3)
  > Support a subset of Markdown inside `intro:` frontmatter
- [x] Category titles (#7)
  > Show category names in in `<RelatedPostsGroup />`
  
## :fire: Syntax highlighting

- [x] Prism.js support
  > Highlight code via prism.js
- [x] Loading prism from CDN
  > Load prism.js from cdn.jsdelivr.net, because it requires `<script data-manual>`
- [x] Support all prism languages
  > Dynamically load languages based on what code blocks are in the page

## :fire: CSS issues

- [x] Margin problem (#4)
  > Bug: Margins around headings are different
- [x] Responsive styled-jsx (#4)
  > Bug: some components styled via styled-jsx weren't being responsive
- [ ] `.-prime` class for sections
- [x] Fix borders on top of `<p>`
- [ ] Icons!
- [x] Proper font-faces in mobile
  > Fix monospace fonts not looking good on iOS/Android

## :fire: Aliases

- [ ] Alias redirection
  > Allow aliases to redirect (`/gpg` → `gnupg`). See [example](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-redirects/gatsby-node.js#L9)
- [ ] Display aliases properly
  > Make aliases obvious in the home page listing

----

## Meta tags

- [x] Show proper `<title>` in cheatsheets
  > Show title as *Vim cheatsheet*
- [x] Show proper `<title>` in home page
  > Show title as *Devhints — TL;DR for developer documentation*
- [ ] Support `keywords` frontmatter in cheatsheets
  > Allow an array of strings (eg, `keywords: [text, editor]`) and generate meta keywords from it
- [ ] Generate `<meta>` description in cheatsheets
  > Generate descriptions from keywords, intro, and other relevant frontmatter

## 404 page

- [x] Link to search on npm, etc
  > When visiting a 404, link to extenal sites
- [ ] Additional styling

## Nav bar

- [ ] "Edit in GitHub" button
  > Allow visitors to submit PR's to cheatsheets
- [ ] Share in Twitter/Facebook
  > Because why not?

## Home page

- [x] Tooltips via hint.css
  > Tooltips for things like 'Updated' or 'Edit on GitHub'
  
- [ ] Search
  > Let users search using Lunr
  
- [ ] Featured pages
- [ ] "See something missing?"
- [ ] Announcements
- [ ] Codefund.io integration
- [ ] Show <title>
- [ ] Hide "Hidden" category

## Devops

- [x] Deployment pipeline
  > Allow gh-pages deploying via CI
- [x] Support custom `CNAME`s
  > Allow deploying to domains like devhints.io

## Documentation

- [ ] Revisit `CONTRIBUTING.md`
- [ ] Readme for rehype-table-separators
- [ ] Readme for rehype-decorate
- [ ] Readme for rehype-wrapify

## rehype-decorate

- [x] Support `.-four-column`
- [ ] Support `a.-crosslink`
- [ ] Support attaching to paragraphs (`.-setup`)

## Misc

- [ ] Show "WIP" messages in cheatsheet
  > If a sheet's tagged with *WIP*, show a work-in-progress disclaimer
- [ ] `<MarkdownBody />` component
  > Dynamically-load MarkdownBody styles via styled-jsx

## Search

- ...TBD

## Commenting

- [ ] Disqus integration
  > Allow visitors to comment via Disqus

----

See #11 for TODO's for future milestones.

**Comment by itsPR** [comment]
@rstacruz It's great to see the project is switching to Gatsby. Gatsby is so awesome. Would like to know when will be the tentative release date for devhints V1.0 with Gatsby?
