### ISSUE TITLE
TODO (future)

### ISSUE THREAD

**Issue by rstacruz** [rstacruz/devhints-engine#11]
Features for consideration in future milestones:

## Sheet page

- [ ] Support "authors" frontmatter
  > Add a special thanks section if `authors:` is available

## Home page

- [ ] Redesign featured pages list
  > Improve appearance of the featured cheatsheets section

## Misc

- [ ] DuckDuckGo cheatsheets integration
  > [Example](https://next.duckduckgo.com/?q=tmux+cheatsheet&ia=cheatsheet&iax=1#zero_click_wrapper), [List](https://github.com/duckduckgo/zeroclickinfo-goodies/tree/master/share/goodie/cheat_sheets/json)
- [ ] Preload prism.js
  > Attach Prism's files as `<link rel='preload' href='...'>`
